### ISSUE TITLE
Add `description`s to Open API schema

### ISSUE THREAD

**Issue by keunes** [OpenPodcastAPI/api-specs#117]
The [Podcast Index API specs](https://podcastindex-org.github.io/docs-api/) has explanations for each field in their API explorer. That is handy; you can just use the explorer, without having to delve into the documentation.

We can also add these descriptions in the fields of response/schema definitions, and they'll show up in the explorer:
```
guid:
          type: string
          format: guid
          description: The unique identifier (guid) for the subscription, as declared in the feed or generated by the server
```
