### ISSUE TITLE
Set up PR deployments

### ISSUE THREAD

**Issue by Sporiff** [OpenPodcastAPI/api-specs#28]
It would be nice to be able to deploy changes made in a PR to a preview environment so that contributors can see the rendered output when reviewing a PR. Some actions such as [PR Preview Action](https://github.com/rossjrw/pr-preview-action) exist to help with this already, so we might be able to use something like the following:

```yaml
# .github/workflows/preview.yml
name: Deploy PR previews

on:
  # Runs on pull requests targeting the default branch
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: preview-${{ github.ref }}
  cancel-in-progress: false

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-preview:
    runs-on: ubuntu-20.04
    steps:
      # Checkout the branch
      - name: Checkout
        uses: actions/checkout@v3
      # Setup Poetry for dependencies
      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v8
      # Build the site with Poetry
      - name: Build html
        run: |
          cd docs
          poetry install
          poetry run make html
      # Deploy the preview to a subsite
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: _build/html
          preview-branch: main
          umbrella-dir: docs
          action: auto
```
